# Generated by Django 5.1.15 on 2026-07-19 00:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Calibration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.CharField(
                        help_text="The person, object, idea, or statement being tested.",
                        max_length=300,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("strong", "Strong (True / Yes / Positive)"),
                            ("weak", "Weak (False / No / Negative)"),
                        ],
                        help_text="Strong = true/resonant; Weak = false/dissonant.",
                        max_length=10,
                    ),
                ),
                (
                    "calibration_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Numerical calibration (1–1000) on Hawkins' Map of Consciousness.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("o_ring", "O-Ring Test (two-person)"),
                            ("finger_over_finger", "Finger-over-Finger"),
                            ("sway", "Sway Test"),
                            ("interlocking_o", "Interlocking O-Ring (solo)"),
                            ("proxy", "Proxy / Surrogate Testing"),
                            ("other", "Other"),
                        ],
                        default="o_ring",
                        help_text="Method used for this test.",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("place", "Place"),
                            ("food", "Food / Supplement"),
                            ("idea", "Idea / Concept"),
                            ("book", "Book / Media"),
                            ("substance", "Substance"),
                            ("entity", "Entity / Organization"),
                            ("practice", "Practice / Technique"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Context or observations."
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Only Me"),
                            ("public", "Community (Public)"),
                        ],
                        default="private",
                        help_text="PRIVATE = only you; PUBLIC = appears in Community DB.",
                        max_length=10,
                    ),
                ),
                (
                    "verification_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of community verifications."
                    ),
                ),
                (
                    "flag_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times flagged for review."
                    ),
                ),
                (
                    "is_removed",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete: hidden from public when True.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the test. Null for anonymous.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "calibrations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject"], name="calibration_subject_419415_idx"
                    ),
                    models.Index(
                        fields=["category"], name="calibration_categor_b0a8e6_idx"
                    ),
                    models.Index(
                        fields=["visibility"], name="calibration_visibil_70cbb3_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="calibration_created_f668ee_idx"
                    ),
                    models.Index(
                        fields=["result"], name="calibration_result_cf7041_idx"
                    ),
                ],
            },
        ),
    ]
