# Generated by Django 5.1.15 on 2026-07-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="karma",
            field=models.IntegerField(default=0, help_text="Community trust score"),
        ),
        migrations.AddField(
            model_name="user",
            name="testing_method",
            field=models.CharField(
                choices=[
                    ("o_ring", "O-Ring Test (two-person)"),
                    ("finger_over_finger", "Finger-over-Finger"),
                    ("sway", "Sway Test"),
                    ("interlocking_o", "Interlocking O-Ring (solo)"),
                    ("proxy", "Proxy / Surrogate Testing"),
                    ("other", "Other"),
                ],
                default="o_ring",
                help_text="Preferred muscle testing method",
                max_length=30,
            ),
        ),
    ]
